### ISSUE TITLE
Disable Pidgin Notification if responding in gnome shell

### ISSUE THREAD

**Issue by dethredic** [kagesenshi/gnome-shell-extensions-pidgin#7]
If I respond to a message via the gnome shell popup thing (black thing in the bottom of the screen), is it possible to clear the pidgin notifications (make the icon sop flashing etc)?

**Comment by kagesenshi** [comment]
frankly speaking, I have no idea how .. >.<

**Comment by ildar** [comment]
I suggest finding out the DBus call to do that and do that. Maybe "purple-send" tool can help.

**Comment by kagesenshi** [comment]
figured out how to flush this when i was poking on it today .. 

notification is now cleared when you focus the notification or replying text :)

**Comment by ildar** [comment]
You sure? Mine doesn't work (the GIT HEAD).
Plz contact me.

**Comment by kagesenshi** [comment]
probably we're referring to different notifications .. the changes i added was to clear the Unseen status of the conversation.

the notification status by this extension is cleared for me. https://extensions.gnome.org/extension/170/pidgin-peristent-notification/

However, if you are referring to the star icon at top right of the buddly list if you have pidgin configured to not display the conversation window by default. well, that is not clearable i think, because it is meant to unhide the conversation.

**Comment by ildar** [comment]
I see. I mainly concerned of the Pidgin icon in the TRAY. Is it possible?

**Comment by kagesenshi** [comment]
erm .. i think thats not clearable neither .. 

what i did in my setup is to simply disable pidgin tray icon as it is not quite needed anymore with the pidgin persistent notification extension .. 

theres a little annoyance with the persistent notification extension which turns red even with slightest change in conversation. but i think i'll be sending a fix to the developer to make it behave better ..

**Comment by ildar** [comment]
but then how do you evoke the Buddy List?

**Comment by kagesenshi** [comment]
if you disable the tray icon, the buddy list is always around in one of the workspace. Switching to the buddy list is like switching to any normal windows.

Ideally is to have pidgin integration with the overview contact search. but that is for later time i guess.

**Comment by ildar** [comment]
Join: https://github.com/githubnemo/Pidgin-Persistent-Notification/issues/2
